AppView/Models/ErrorViewModel.cs
namespace AppView.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AppView/Controllers/HomeController.cs
using AppView.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AppView.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AppView/Controllers/SanPhamController.cs
using AppData.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace AppView.Controllers
{
    public class SanPhamController : Controller
    {
        public SanPhamController()
        {
            
        }
        // GET: SanPhamController
        public async Task<ActionResult> Index1()
        {
            string requestURL = "https://localhost:7176/api/SanPham/get-all";
            var httpClient = new HttpClient();
            var reponse = await httpClient.GetAsync(requestURL);
            string apiData = await reponse.Content.ReadAsStringAsync();
            var sanphams = JsonConvert.DeserializeObject<List<SanPham>>(apiData);
            return View(sanphams);
        }

        // GET: SanPhamController/Details/5
        public async Task<ActionResult> Details(string MaSP)
        {
            string requestURL = $"https://localhost:7176/api/SanPham/get-by-masp?MaSP={MaSP}";
            var httpClient = new HttpClient();
            var reponse = await httpClient.GetAsync(requestURL);
            string apiData = await reponse.Content.ReadAsStringAsync();
            var sanphams = JsonConvert.DeserializeObject<SanPham>(apiData);
            return View(sanphams);
        }

        // GET: SanPhamController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SanPhamController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(SanPham sp)
        {
            string requestURL = $"https://localhost:7176/api/SanPham/post-by-masp";
            var httpsClient = new HttpClient();
            var obj = JsonConvert.SerializeObject(sp);
            var reponse = await httpsClient.PostAsJsonAsync(requestURL, sp);
            if (reponse.IsSuccessStatusCode)
            {
                return RedirectToAction("Index1");
            }
            else return BadRequest(reponse);
        }

        // GET: SanPhamController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: SanPhamController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(string MaSP, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: SanPhamController/Delete/5
        [HttpGet]
        public async Task<ActionResult> Delete(string MaSP)
        {
            string requestURL = $"https://localhost:7176/api/SanPham/{MaSP}";
            var httpsClient = new HttpClient();
            var reponse = await httpsClient.GetAsync(requestURL);
            string apiData = await httpsClient.GetStringAsync(requestURL);
            if (reponse.IsSuccessStatusCode)
            {
                return RedirectToAction("Index1");
            }else return BadRequest(reponse);
            
        }

        // POST: SanPhamController/Delete/5
        



    }
}

AppView/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AppView/Views/SanPham/Create.cshtml
@model AppData.Models.SanPham

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>SanPham</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MaSP" class="control-label"></label>
                <input asp-for="MaSP" class="form-control" />
                <span asp-validation-for="MaSP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TenSP" class="control-label"></label>
                <input asp-for="TenSP" class="form-control" />
                <span asp-validation-for="TenSP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gia" class="control-label"></label>
                <input asp-for="Gia" class="form-control" />
                <span asp-validation-for="Gia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SLTon" class="control-label"></label>
                <input asp-for="SLTon" class="form-control" />
                <span asp-validation-for="SLTon" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NSX" class="control-label"></label>
                <input asp-for="NSX" class="form-control" />
                <span asp-validation-for="NSX" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ThuongHieu" class="control-label"></label>
                <input asp-for="ThuongHieu" class="form-control" />
                <span asp-validation-for="ThuongHieu" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index1">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AppView/Views/SanPham/Details.cshtml
@model AppData.Models.SanPham

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>SanPham</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MaSP)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MaSP)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TenSP)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TenSP)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gia)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SLTon)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SLTon)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NSX)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NSX)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ThuongHieu)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ThuongHieu)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new {  id = Model.MaSP }) |
    <a asp-action="Index">Back to List</a>
</div>

AppView/Views/SanPham/Edit.cshtml
@model AppData.Models.SanPham

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>SanPham</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MaSP" class="control-label"></label>
                <input asp-for="MaSP" class="form-control" />
                <span asp-validation-for="MaSP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TenSP" class="control-label"></label>
                <input asp-for="TenSP" class="form-control" />
                <span asp-validation-for="TenSP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gia" class="control-label"></label>
                <input asp-for="Gia" class="form-control" />
                <span asp-validation-for="Gia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SLTon" class="control-label"></label>
                <input asp-for="SLTon" class="form-control" />
                <span asp-validation-for="SLTon" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NSX" class="control-label"></label>
                <input asp-for="NSX" class="form-control" />
                <span asp-validation-for="NSX" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ThuongHieu" class="control-label"></label>
                <input asp-for="ThuongHieu" class="form-control" />
                <span asp-validation-for="ThuongHieu" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AppView/Views/SanPham/Index1.cshtml
@model IEnumerable<AppData.Models.SanPham>

@{
    ViewData["Title"] = "Index1";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.MaSP)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TenSP)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gia)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SLTon)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NSX)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ThuongHieu)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MaSP)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TenSP)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gia)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SLTon)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NSX)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ThuongHieu)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new {  id=item.MaSP  }) |
                @Html.ActionLink("Details", "Details", new {  id=item.MaSP }) |
                @Html.ActionLink("Delete", "Delete", new {  id=item.MaSP  })
            </td>
        </tr>
}
    </tbody>
</table>

AppView/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AppView</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AppView.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AppView</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SanPham" asp-action="Index1">Xem SP</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AppView - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>